### ISSUE TITLE
Late notifications when turning notifications on, off, and on in a single session

### ISSUE THREAD

**Issue by ericanderson2** [ericanderson2/leet-friends#3]
Version: Firefox 1.4, likely a bug for all browsers

**Summary**
If notifications for a friend are on, and then turned off, and then turned back on in a single browser session, the user will receive notifications from the time when notifications were off.

**Steps to reproduce**
1. Add a yourself as a friend
2. Turn on notifications for yourself
3. Wait at least 30 seconds, then turn off notifications
4. Submit a problem on LeetCode
5. Wait at least 30 seconds, then turn notifications back on

What should happen: You should not receive a notification.

What happens: You receive a notification

**Ideas to fix**
1. Check the current time before sending a notification, and don't send a notification if it's late
2. Update last_submitted_time in background.js when a friend's notifications are turned off (might be difficult / impossible)

**Comment by ericanderson2** [comment]
This bug only happens in very specific circumstances and only results in a late notification. I may or may not fix it.

**Comment by leftover19** [comment]
Hi
I made a similar extension myself, just a few days ago. I went through your code  and it's really optimized. can I contact you somehow?
I just want to learn how to do few things. 
sorry for bothering you here. Will delete this comment later.

**Comment by ericanderson2** [comment]
This does not seem to be worth the effort to fix, seeing as though it is barely even a bug.
